apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: databridge

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/name: databridge
  app.kubernetes.io/part-of: databridge
  app.kubernetes.io/managed-by: kustomize

images:
  - name: databridge
    newName: registry.example.com/databridge
    newTag: v1.0.0
