apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: databridge
  namespace: databridge
  labels:
    app: databridge
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: databridge
      component: backend
