apiVersion: v1
kind: Secret
metadata:
  name: databridge-secret
  namespace: databridge
type: Opaque
stringData:
  # Replace with actual values
  DB_PASSWORD: "changeme"
  API_KEY: "changeme"
  JWT_SECRET: "changeme"
