apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: databridge
  namespace: databridge
  labels:
    app: databridge
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: databridge
      component: backend
  endpoints:
  - port: http
    path: /api/metrics
    interval: 15s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - databridge
