name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Build Backend
      run: |
        GOOS=linux GOARCH=amd64 go build -o build/databridge-linux-amd64 ./cmd/databridge
        GOOS=darwin GOARCH=amd64 go build -o build/databridge-darwin-amd64 ./cmd/databridge
        GOOS=darwin GOARCH=arm64 go build -o build/databridge-darwin-arm64 ./cmd/databridge
        GOOS=windows GOARCH=amd64 go build -o build/databridge-windows-amd64.exe ./cmd/databridge

    - name: Build Frontend
      run: |
        cd frontend
        npm ci
        npm run build
        tar -czf ../build/frontend-dist.tar.gz .next

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/databridge-linux-amd64
          build/databridge-darwin-amd64
          build/databridge-darwin-arm64
          build/databridge-windows-amd64.exe
          build/frontend-dist.tar.gz
        generate_release_notes: true
